extends:
  - '@commitlint/config-conventional'
rules:
  'references-empty':
    - 2
    - 'never'
  subject-case:
    - 2
    - 'never'
    - - 'start-case'
      - 'sentence-case'
      - 'pascal-case'
